modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="crilloaugu_remote_workspace"
version="1.0.0"
displayName="crilloaugu. remote workspace"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Augus, MCreator"

[[dependencies.crilloaugu_remote_workspace]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




